version: '3.1'
services:
  email-sender:
    container_name: email-sender
    image: ${DOCKER_REPOSITORY}:latest
    hostname: email.sender
    ports:
      - "8003:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - GMAIL_EMAIL=${GMAIL_EMAIL}
      - GMAIL_TOKEN=${GMAIL_TOKEN}
      - LOGTAIL_APP_NAME=${LOGTAIL_APP_NAME}
      - LOGTAIL_LOGS=${LOGTAIL_LOGS}
      - LOGGING_LEVEL=${LOGGING_LEVEL}
      - SHOW_UTILS_EXCEPTION_STACKTRACE=${SHOW_UTILS_EXCEPTION_STACKTRACE}
      - GCLOUD_PROJECT=${GCLOUD_PROJECT}
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
      - APP_ENV=${APP_ENV}
      - STRAPI_AUTH_TOKEN=${STRAPI_AUTH_TOKEN}
    networks:
      docker-network:
        aliases:
          - email.sender
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.email-sender.rule=Host(`email-sender.giovannilamarmora.com`)"
      - "traefik.http.services.email-sender.loadbalancer.server.port=8080"
      - "traefik.http.routers.email-sender.middlewares=cloudflarewarp@file,geoblock@file"

networks:
  docker-network:
    external: true