version: '3.9'
services:
  email-sender:
    container_name: email-sender
    image: ${DOCKER_REPOSITORY}:latest
    hostname: email.sender
    ports:
      - "8003:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SERVER_EMAIL=${SERVER_EMAIL}
      - SERVER_TOKEN=${SERVER_TOKEN}
      - SENDER_EMAILS=${SENDER_EMAILS}
      - LOGGING_LEVEL=${LOGGING_LEVEL}
      - SHOW_UTILS_EXCEPTION_STACKTRACE=${SHOW_UTILS_EXCEPTION_STACKTRACE}
      - GCLOUD_PROJECT=${GCLOUD_PROJECT}
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
      - APP_ENV=${APP_ENV}
      - STRAPI_AUTH_TOKEN=${STRAPI_AUTH_TOKEN}
    volumes:
      # Monta il volume "microservice" nella cartella /secrets (in sola lettura)
      - microservice:/secrets:ro
    networks:
      docker-network:
        aliases:
          - email.sender

networks:
  docker-network:
    external: true

volumes:
  microservice:
    external: true