version: '3.1'
services:
  backend-service:
    container_name: email-sender
    image: ${DOCKER_REPOSITORY}:latest
    hostname: email.sender
    ports:
      - "8003:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE}
      - GMAIL_EMAIL=${GMAIL_EMAIL}
      - GMAIL_TOKEN=${GMAIL_TOKEN}
      - LOGTAIL_APP_NAME=${LOGTAIL_APP_NAME}
      - LOGTAIL_LOGS=${LOGTAIL_LOGS}
      - LOGGING_LEVEL=${LOGGING_LEVEL}
      - SHOW_UTILS_EXCEPTION_STACKTRACE=${SHOW_UTILS_EXCEPTION_STACKTRACE}
    networks:
      docker-network:
        aliases:
          - email.sender

networks:
  docker-network:
    external: true