env: ${APP_ENV:Deploy} # Used for Google Cloud LOG
spring:
  mail:
    host: ${SMTP_HOST}
    port: ${SMTP_PORT}
    username: ${SERVER_EMAIL}
    password: ${SERVER_TOKEN}
    sender-emails: ${SENDER_EMAILS}

filter:
  requestResponse:
    enabled: true
    shouldNotFilter: "**/swagger-ui/**,/api-docs,**/api-docs/**,*/,*/css/*,*/js/*,*/images/*,*/favicon.ico,/index.html"

logging:
  config: classpath:logback-google.xml # classpath:logback-google.xml, classpath:logback-logtail.xml
  level:
    com.giovannilamarmora.dispatch.emailsender: ${LOGGING_LEVEL}
    io.github.giovannilamarmora.utils: ${LOGGING_LEVEL}

app:
  version: @project.version@ # Show Project Version
  exception:
    stacktrace: ${SHOW_UTILS_EXCEPTION_STACKTRACE} # Active StackTrace in Response

rest:
  client:
    strapi:
      baseUrl: http://app.strapi.cms:1337